In [2]:
import numpy as np
import pandas as pd

#import data
pop = pd.read_csv('state-population.csv')
area = pd.read_csv('state-areas.csv')
abbrev = pd.read_csv('state-abbrevs.csv')

In [3]:
merged = pd.merge(area, abbrev, how='outer')

merged[merged['abbreviation'].isnull()].head()

          state  area (sq. mi) abbreviation
39  Puerto Rico           3515          NaN

In [8]:
#ranking population density from the year 2010
merged = pd.merge(area, abbrev, how='outer')

#Finding Null Values
merged.isnull().any()
merged[merged['abbreviation'].isnull()].head() #Puerto Rico has no abbreviation
merged.loc[merged['state'] == 'Puerto Rico' , 'abbreviation' ] = 'PR'

#merging population and merged
final = pd.merge(pop, merged, how='outer', left_on='state/region', right_on='abbreviation')
final.drop('abbreviation', axis=1, inplace=True) #drop the duplicate abbreviation
final.dropna(inplace=True) #Drop USA values cause not a state
#final.head()

In [9]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending=False, inplace= True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

Cleaning Titantic dataset

In [1]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset('titanic')

#df.info()
#df.isnull().any()
#missing age, embarked, deck, and embarked town

#dropping data
#input age with median age of passengar class
df['age'] = df['age'].fillna(df.groupby('pclass')['age'].transform('median'))
df.drop('deck', axis=1) #most of deck is missing so might as well drop
df.dropna(subset=['embarked', 'embark_town']) #subset targets specific rows

#convert categorical data to numeric values
df['sex'] = df['sex'].map({'male' : 1 , 'female' : 0})
df['class'] = df['class'].map({'Third' : 3, 'Second' : 2, 'First':1})

#drop redunant columns
df.drop(columns=['adult_male', 'who', 'alive', 'alone', 'embarked'], axis=1, inplace=True)
df

,survived,pclass,sex,age,sibsp,parch,fare,class,deck,embark_town
0,0,3,1,22.0,1,0,7.2500,3,NaN,Southampton
1,1,1,0,38.0,1,0,71.2833,1,C,Cherbourg
2,1,3,0,26.0,0,0,7.9250,3,NaN,Southampton
3,1,1,0,35.0,1,0,53.1000,1,C,Southampton
4,0,3,1,35.0,0,0,8.0500,3,NaN,Southampton
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,2,NaN,Southampton
887,1,1,0,19.0,0,0,30.0000,1,B,Southampton
888,0,3,0,24.0,1,2,23.4500,3,NaN,Southampton
889,1,1,1,26.0,0,0,30.0000,1,C,Cherbourg
890,0,3,1,32.0,0,0,7.7500,3,NaN,Queenstown